version: '3.4'

services:
  crimeevent:
    image: ${DOCKER_REGISTRY-}crimeevent
    build:
      context: .
      dockerfile: CrimeEvent/Dockerfile
  
  lawenforcement:
    image: ${DOCKER_REGISTRY-}lawenforcement
    build:
      context: .
      dockerfile: LawEnforcement/Dockerfile

  mongo:
   image: mongo
   restart: always
   ports:
     - 27017:27017

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    restart: on-failure
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"