// <auto-generated />
using LawEnforcementDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawEnforcementDB.Migrations
{
    [DbContext(typeof(LawEnforcementContext))]
    [Migration("20221026162048_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LawEnforcementDB.Entities.CrimeEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LawEnforcementModelLawEnforcementID")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("LawEnforcementModelLawEnforcementID");

                    b.ToTable("CrimeEvents");
                });

            modelBuilder.Entity("LawEnforcementDB.Entities.LawEnforcementModel", b =>
                {
                    b.Property<string>("LawEnforcementID")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("EnforcementRank")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("LawEnforcementID");

                    b.ToTable("LawEnforcementModels");

                    b.HasData(
                        new
                        {
                            LawEnforcementID = "AAS11421",
                            EnforcementRank = "SERGEANT"
                        },
                        new
                        {
                            LawEnforcementID = "AGF66633",
                            EnforcementRank = "LIEUTENANT"
                        },
                        new
                        {
                            LawEnforcementID = "ANC66431",
                            EnforcementRank = "CAPTAIN"
                        },
                        new
                        {
                            LawEnforcementID = "AZZ33405",
                            EnforcementRank = "CORPORAL"
                        },
                        new
                        {
                            LawEnforcementID = "GDS11643",
                            EnforcementRank = "PATROL OFFICER"
                        },
                        new
                        {
                            LawEnforcementID = "HJS18891",
                            EnforcementRank = "POLICE DETECTIVE"
                        },
                        new
                        {
                            LawEnforcementID = "LUS33721",
                            EnforcementRank = "SERGEANT"
                        },
                        new
                        {
                            LawEnforcementID = "EES11521",
                            EnforcementRank = "LIEUTENANT"
                        },
                        new
                        {
                            LawEnforcementID = "XVS16321",
                            EnforcementRank = "LIEUTENANT"
                        });
                });

            modelBuilder.Entity("LawEnforcementDB.Entities.CrimeEvent", b =>
                {
                    b.HasOne("LawEnforcementDB.Entities.LawEnforcementModel", null)
                        .WithMany("CrimeEventList")
                        .HasForeignKey("LawEnforcementModelLawEnforcementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LawEnforcementDB.Entities.LawEnforcementModel", b =>
                {
                    b.Navigation("CrimeEventList");
                });
#pragma warning restore 612, 618
        }
    }
}
