// <auto-generated />
using LawEnforcementSqlDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawEnforcementDB.Migrations
{
    [DbContext(typeof(LawEnforcementContext))]
    partial class LawEnforcementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LawEnforcementDB.Entities.CrimeEventModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LawEnforcementModelEnforcementId")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("LawEnforcementModelEnforcementId");

                    b.ToTable("CrimeEventModel");
                });

            modelBuilder.Entity("LawEnforcementSqlDB.Entities.LawEnforcementModel", b =>
                {
                    b.Property<string>("EnforcementId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("EnforcementRank")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("EnforcementId");

                    b.ToTable("LawEnforcementModels");
                });

            modelBuilder.Entity("LawEnforcementDB.Entities.CrimeEventModel", b =>
                {
                    b.HasOne("LawEnforcementSqlDB.Entities.LawEnforcementModel", null)
                        .WithMany("CrimeEventList")
                        .HasForeignKey("LawEnforcementModelEnforcementId");
                });

            modelBuilder.Entity("LawEnforcementSqlDB.Entities.LawEnforcementModel", b =>
                {
                    b.Navigation("CrimeEventList");
                });
#pragma warning restore 612, 618
        }
    }
}
